services:
  - type: web
    name: eatoessaas
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgres://eatoessaas_db_user:ZmNir2UefodhQNJnQaVD690Nb78qzULr@dpg-cv06fp2n91rc73fl5en0-a.oregon-postgres.render.com/eatoessaas_db
      - key: PORT
        value: 3000
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true